name: Publish SDK to GitHub Packages (NPM)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@${{ github.repository_owner }}'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./log-client

      - name: Build SDK
        run: pnpm run build
        working-directory: ./log-client
        continue-on-error: true # In case build script is not in package.json yet

      - name: Publish to GitHub Packages
        run: npm publish
        working-directory: ./log-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
